volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    container_name: foodgram-psql
    image: postgres:17.2-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend:
    container_name: foodgram-back
    build: ../backend/
    env_file: .env
    environment:
      - IS_DOCKER=true  # Tell Django not to search for .env as it loaded by Docker.
    volumes:
      - ../backend/foodgram:/app/foodgram/  # Hot-reload.
      - static:/app/foodgram/static/        # Static files.
    depends_on:
      - postgres

  frontend:
    container_name: foodgram-front
    build: ../frontend/
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram_proxy
    image: nginx:1.25.4-alpine
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html/scripts/
      - media:/usr/share/nginx/html/media/
    depends_on:
      - backend