volumes:
  pg_data:
  back_static:
  back_media:

networks:
  default:
    driver: bridge
    name: foodgram_network

services:
  postgres:
    container_name: foodgram-psql
    image: postgres:17.2-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - default

  backend:
    container_name: foodgram-back
    build: ../backend/
    env_file: .env
    environment:
      - IS_DOCKER=true  # Tell Django not to search for .env as it loaded by Docker.
    volumes:
      - ../backend/foodgram:/app/foodgram/    # Hot-reload.
      - back_static:/app/foodgram/static/  # Static files.
    depends_on:
      - postgres
    networks:
      - default

  frontend:
    container_name: foodgram-front
    build: ../frontend/
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram_proxy
    image: nginx:1.25.4-alpine
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - back_static:/usr/share/nginx/html/api/static/
      - back_media:/usr/share/nginx/html/api/media/
    depends_on:
      - backend
    networks:
      - default