# Generated by Django 5.1.7 on 2025-04-11 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('author', models.ForeignKey(help_text='Автор, на которого подписан пользователь.', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('subscriber', models.ForeignKey(help_text='Пользователь, подписанный на автора.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('author__username',),
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'author'), name='uq_subscription_subscriber_author'), models.CheckConstraint(condition=models.Q(('subscriber', models.F('author')), _negated=True), name='check_subscription_prevent_self_subscription')],
            },
        ),
    ]
