name: Main workflow

on:
  push:
    branches:
      - master

jobs:
  backend_tests:
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      # Preparation.
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Check PEP8 before actual tests.
      - name: Check code with flake8
        run: |
          cd ./backend/foodgram/
          python -m pip install --upgrade pip
          pip install flake8 --no-cache-dir --quiet
          flake8 . --max-line-length=80

      # Run testing server.
      - name: Install dependencies
        run: pip install -r ./backend/requirements.txt --quiet
      - name: Set up environment
        run: cp ./infra/.env.example ./infra/.env
      - name: Migrate
        run: python ./backend/foodgram/manage.py migrate
      - name: Load example data
        run: python ./backend/foodgram/manage.py loaddata ./backend/foodgram/db_example.json
      - name: Start server in background
        run: |
          cd ./backend/foodgram/
          nohup python manage.py runserver 127.0.0.1:8000 &
      - name: Wait for server to be ready
        run: |
          echo "Waiting for server..."
          sleep 10
          curl --fail http://127.0.0.1:8000/api/ || (echo "Server not responding" && exit 1)

      # Run API tests.
      - name: Install Newman
        run: npm install -g newman
      - name: Run Postman Collection
        continue-on-error: true
        run: newman run ./postman_collection/foodgram.postman_collection.json --reporters cli

  backend_build_and_push_to_docker_hub:
    name: Push backend Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: backend_tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-back:latest

  frontend_build_and_push_to_docker_hub:
    name: Push frontend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-front:latest

  notify_in_telegram:
    runs-on: ubuntu-latest
    needs:
      - backend_build_and_push_to_docker_hub
      - frontend_build_and_push_to_docker_hub
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ **Foodgram** CI/CD has finished!
            📦 DockerHub updated.
            🔗 Release: https://hub.docker.com/u/${{ secrets.DOCKER_USERNAME }}