name: Main workflow

on:
  push:
    branches:
      - master

jobs:
  backend_tests:
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Check code with flake8
        run: |
          cd backend
          pip install flake8 
          flake8 . --max-line-length=80
      - name: Install Newman
        run: npm install -g newman
      - name: Run Postman Collection
        run: |
          newman run ./postman_collection/foodgram.postman_collection.json \
            --environment postman/environment.json \
            --reporters cli

  backend_build_and_push_to_docker_hub:
    name: Push backend Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: backend_tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-back:latest

  frontend_build_and_push_to_docker_hub:
    name: Push frontend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-front:latest

  notify_in_telegram:
    runs-on: ubuntu-latest
    needs:
      - backend_build_and_push_to_docker_hub
      - frontend_build_and_push_to_docker_hub
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ **Foodgram** CI/CD has finished!
            📦 DockerHub updated.
            🔗 Release: https://hub.docker.com/u/${{ secrets.DOCKER_USERNAME }}